version: "2.4"
services:
  sindri:
    build:
      context: .
      network: host
    volumes:
      - ./:/root/nuttxspace/
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0  
    ulimits:
      nofile:
        soft: 64000
        hard: 64000


