version: '3'
services:
  sindri:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
      network: host
    volumes:
      - ./:/root/nuttxspace/
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0  
    ulimits:
      nofile:
        soft: 64000
        hard: 64000


