version: "2.4"
services:
  sindri:
    build:
      context: .
      network: host
    volumes:
      - ./:/root/nuttxspace/app_user/
    ulimits:
      nofile:
        soft: 64000
        hard: 64000


